version: '3.7'
services:
    apache-php74:
        build:
            context: docker/apache
        depends_on:
            - mysql57
        volumes:
            - type: bind
              source: .
              target: /var/www/html/
        ports:
            - 8080:80

    keycloak:
        image: quay.io/keycloak/keycloak:14.0.0
        volumes:
            - ~/Projects/tmp/mysql57_dblemenu:/var/lib/mysql
            - ./docker/mysql/config:/etc/mysql/conf.d
        ports:
            - "8081:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin


    mysql57:
        build:
            context: docker/mysql
        volumes:
            - ~/Projects/tmp/mysql57_dblemenu:/var/lib/mysql
            - ./docker/mysql/config:/etc/mysql/conf.d
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root

#https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects
